backend:
  enabled: true
  serviceAccount:
    create: true
orderfrontendapp:
  enabled: false
pythonSubscriber:
  enabled: false
service:
  enabled: true  # Enable the service
  port: 8080     # The port the service exposes
  targetPort: 8080  # Maps to the backend containerPort