{{- if .Values.pythonSubscriber.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-subscriber
  labels:
    app: {{ .Release.Name }}-python-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-python-subscriber
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python-subscriber"
        dapr.io/app-port: "5001"
        dapr.io/app-protocol: "http"
        dapr.io/metrics-enabled: "true"
    spec:
      containers:
      - name: python-subscriber
        image: reisenberg123/dapr-traffic-control-python-subscriber:1.0
        ports:
        - containerPort: 5001
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: "http"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
{{- end }}